Add ocm-eks role and enable EKS cluster import
open-cluster-management/ocmplus.cm pull request #20
Opened 2021-11-29 22:08 UTC by taragu

Co-authored-by: Tara Gu <tgu@redhat.com>
Co-authored-by: Hao Liu <haoli@redhat.com>
Co-authored-by: Crystal Chun <cchun@redhat.com>
Co-authored-by: Hanqiu Zhang <hanzhang@redhat.com>

/cc @TheRealHaoLiu @CrystalChun @hanqiuzh

2021-11-30 14:37 UTC, TheRealHaoLiu commented on plugins/module_utils/import_utils.py
> +# secret_api = client.resources.get(api_version="v1", kind="Secret")
please delete this

2021-11-30 14:39 UTC, TheRealHaoLiu commented on plugins/modules/import_eks.py
> +    type:
need to complete this part of the doc

2021-11-30 14:50 UTC, TheRealHaoLiu commented on plugins/modules/import_eks.py
> +    return paginator.paginate(**params).build_full_result()
unused method?

2021-11-30 15:16 UTC, TheRealHaoLiu requested changes
see above comments for the changes we might need

also we need to talk about if we need the roles/ocm-eks if we have a plugin/module since user would use the plugin/modules directly rather than using the roles

also there's an empty file named `eks_utils.py`

2021-11-30 15:20 UTC, TheRealHaoLiu commented
/approve cancel

2021-11-30 18:55 UTC, taragu commented on roles/ocm-eks/tasks/main.yml
> +- debug: msg="{{ hub_result }}"
Correct, users won't be using this so this should be organized under a tests directory under the project, like the amazon.aws module:
<img width="336" alt="Screen Shot 2021-11-30 at 10 53 34 AM" src="https://user-images.githubusercontent.com/6353048/144109805-c7e87c42-9bf8-4e9d-bbc0-0098cc5ff9a6.png">
We can reoganize this into the tests directory either as part of this PR or a followup PR. Any preferences?

2021-11-30 21:06 UTC, taragu commented
PR is updated. I also change the integration test playbook to use a list of eks cluster names.

2021-12-02 15:21 UTC, TheRealHaoLiu approved these changes

2021-12-02 15:22 UTC, merged